exclude: [principle-orig.html, public/img/retired, tags, rick, contact_.html, cdn, node_modules, aws-keys.json, package.json, Gruntfile.js]

title: Jalan Cinta Sanctuary
email: love@thewayoflove.com

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://jalancintasanctuary.com" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

# Server settings
port: 3000

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "unify-v4"
