exclude: [pandoc, project, work, vim, contact_.html, cdn, node_modules, aws-keys.json, package.json, Gruntfile.js]

gems: [ 'jekyll-paginate', 'jekyll-pandoc-multiple-formats' ]

title: Jalan Cinta Sanctuary
email: jalancintasancutary@gmail.com
webmaster: "rmercer33@gmail.com (Rick Mercer)"
editor: "jalancintasanctuary@gmail.com (Sandy Button)"

description: >
  News and Inspiration from Jalan Cinta Sanctuary in Ubud, Bali

baseurl: "/"
url: "https://www.jalancintasanctuary.com"

fbapi: fbapi-com
env: prod

paginate: 4
paginate_path: "blog/post/page:num"

# Build settings
# markdown: kramdown
markdown: pandoc

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true

pandoc:
  skip: true
  impose: false
  output: ./pandoc
  flags: '--smart'
  site_flags: '--toc'
  outputs:
    pdf: '--latex-engine=pdflatex'
    epub:
    markdown:

# Server settings
port: 3000

# Default extension for new posts and pages
post_ext: md
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: unify-blog-post
page_layout: unify-v4

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

