#!/bin/sh

# Inbound email routing rule for WoL account and jalancintasanctuary.com 
# domain at mailgun.com
#
# route inbound mail to rod@mail.jalancintasanctuary.com 
# to rod@thewayoflove.com

curl -s --user 'api:key-5d441d817e61642bedd485c2b2337deb' \
    https://api.mailgun.net/v3/routes \
    -F priority=0 \
    -F description='to' \
    -F expression='match_recipient("rod@mail.jalancintasanctuary.com")' \
    -F action='forward("rod@thewayoflove.com")' \
    -F action='stop()'
